/**
 * Session & Checkpoint Architecture - Type Definitions
 *
 * This file defines the core types for the unified session management system
 * that works across all agent types (PM, Dev, QA, Harness, Merge).
 */

/**
 * Agent types supported by the session system.
 */
export type AgentType = 'pm' | 'investigation' | 'planning' | 'dev' | 'qa' | 'harness' | 'merge'

/**
 * Session types based on what context they're attached to.
 */
export type SessionType = 'feature' | 'task'

/**
 * Task execution states that can have separate sessions.
 */
export type TaskState =
  | 'planning'
  | 'in_dev'
  | 'dev_complete'
  | 'in_qa'
  | 'qa_complete'
  | 'ready_for_merge'
  | 'merged'

/**
 * Verification result summary for message metadata.
 */
export interface VerificationResultSummary {
  checkId: string
  passed: boolean
  error?: string
}

/**
 * Individual chat message in a session.
 */
export interface ChatMessage {
  id: string
  role: 'user' | 'assistant' | 'system'
  content: string
  timestamp: string
  metadata?: {
    agentType?: AgentType
    agentId?: string  // Agent instance ID for tracking (DevAgent)
    taskId?: string   // Task ID for context (DevAgent)
    iteration?: number
    iterationNumber?: number  // Alias for iteration (used by TaskController)
    toolUse?: {
      name: string
      input?: unknown
      result?: unknown
    }
    tokens?: {
      input: number
      output: number
    }
    internal?: boolean  // Don't show in user-facing UI
    verificationResults?: VerificationResultSummary[]  // Results from Ralph Loop iteration
    // Migration metadata
    migratedFrom?: string
    originalTimestamp?: string
    originalType?: string
  }
}

/**
 * Chat session containing recent messages.
 * This file stores only the last N messages (0 to any number).
 * Older messages are compressed into checkpoint.
 */
export interface ChatSession {
  messages: ChatMessage[]
  totalMessages: number  // Total count including compacted ones
  oldestMessageTimestamp?: string  // Timestamp of oldest message in this file
  newestMessageTimestamp?: string  // Timestamp of newest message
}

/**
 * Checkpoint data representing compressed conversation history.
 * This is generated by a compaction agent from old checkpoint + old messages.
 */
export interface Checkpoint {
  version: number  // Checkpoint version for migration
  createdAt: string
  updatedAt: string

  // Compressed summary of work done and remaining
  summary: {
    completed: string[]  // List of completed tasks/actions
    inProgress: string[]  // Currently in progress
    pending: string[]  // Still to do
    blockers: string[]  // Issues blocking progress
    decisions: string[]  // Key decisions made
  }

  // Metadata about what was compacted
  compactionInfo: {
    messagesCompacted: number
    oldestMessageTimestamp: string
    newestMessageTimestamp: string
    compactedAt: string
  }

  // Statistics
  stats: {
    totalCompactions: number
    totalMessages: number
    totalTokens: number
  }
}

/**
 * Session context containing relevant project/feature/task information.
 * This is rebuilt dynamically each time a request is made.
 */
export interface SessionContext {
  projectRoot: string

  // Feature context
  featureId: string
  featureName: string
  featureGoal?: string

  // Task context (optional, for task sessions)
  taskId?: string
  taskTitle?: string
  taskState?: TaskState

  // DAG context
  dagSummary?: string
  dependencies?: string[]
  dependents?: string[]

  // Project files context
  projectStructure?: string
  claudeMd?: string
  projectMd?: string

  // Git context
  recentCommits?: string[]

  // Attachments
  attachments?: string[]
}

/**
 * Agent description containing the system prompt for an agent type.
 * This is static and doesn't change during a session.
 */
export interface AgentDescription {
  agentType: AgentType
  roleInstructions: string
  toolInstructions?: string
  createdAt: string
}

/**
 * Complete session metadata and configuration.
 */
export interface Session {
  id: string  // Format: "{sessionType}-{featureId}-{taskId?}-{state?}"
  type: SessionType
  agentType: AgentType

  // Context references
  featureId: string
  taskId?: string
  taskState?: TaskState

  // Lifecycle
  createdAt: string
  updatedAt: string
  status: 'active' | 'archived'

  // File references (relative paths from session directory)
  files: {
    chat: string  // chat_<sessionId>.json
    checkpoint: string  // checkpoint_<sessionId>.json
    context: string  // context_<sessionId>.json
    agentDescription: string  // agent-description_<sessionId>.json
  }

  // Statistics
  stats: {
    totalMessages: number
    totalTokens: number
    totalCompactions: number
    lastRequestTokens?: number
    lastCompactionAt?: string
  }

  // PM Agent planning metadata (only for PM agent sessions)
  pmMetadata?: {
    complexity?: 'low' | 'medium' | 'high'
    questionsAsked?: number
    questionsRequired?: number
    assessedAt?: string
  }
}

/**
 * Token estimation result for a request.
 */
export interface TokenEstimate {
  systemPrompt: number
  messages: number
  userPrompt: number
  total: number
  limit: number  // 100k tokens
  needsCompaction: boolean
}

/**
 * Complete agent request ready to send to Claude.
 */
export interface AgentRequest {
  systemPrompt: string  // Agent Description + Context + Checkpoint + Messages
  userPrompt: string  // Latest user message
  messages?: ChatMessage[]  // For Messages API format
  tokenEstimate: TokenEstimate
  sessionId: string
}

/**
 * Result of a compaction operation.
 */
export interface CompactionResult {
  success: boolean
  newCheckpoint: Checkpoint
  messagesCompacted: number
  tokensReclaimed: number
  error?: string
}

/**
 * Session creation options.
 */
export interface CreateSessionOptions {
  type: SessionType
  agentType: AgentType
  featureId: string
  taskId?: string
  taskState?: TaskState
}

/**
 * Session update event data.
 */
export interface SessionUpdateEvent {
  sessionId: string
  featureId: string
  taskId?: string
  action: 'created' | 'message_added' | 'compacted' | 'archived'
  timestamp: string
}
